### ISSUE TITLE
New metadata fields for provenance

### ISSUE THREAD

**Issue by IgnacioHeredia** [ai4os/ai4-metadata#55]
In the new metadata version, we can consider adding the new fields for the provenance:
https://github.com/ai4os-hub/ai4os-demo-app/blob/cf87144e1c3975555f7f6f93c2ccf8a7a3640f82/ai4-metadata.yml#L23-L25

```yml
provenance:
  nomad_job: f4b9c17a-1077-11f0-9e04-0242ac120002
  mlflow_run: 5e96fe940dca470aa7d6c16620e82c35
```

Not a priority since we are still using those fields, even if the validator is not checking them.
